services:
  db:
    image: postgres:18-alpine
    container_name: sprintmont_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sprintmont_net

  redis:
    image: redis:alpine
    container_name: sprintmont_cache
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - sprintmont_net

  bucket:
    image: chrislusf/seaweedfs
    container_name: sprintmont_bkt
    restart: unless-stopped
    ports:
      - "8333:8333"
      - "8888:8888"
    command: "server -s3 -filer -master.volumeSizeLimitMB=1024 -volume.max=100 -s3.config=/etc/seaweedfs/s3_config.json"
    volumes:
      - seaweed_data:/data
      - ./seaweedfs_config/s3_config.json:/etc/seaweedfs/s3_config.json
    networks:
      - sprintmont_net

  backend:
    build: ./server
    container_name: sprintmont_be
    restart: unless-stopped
    networks:
      - sprintmont_net
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - bucket

  frontend:
    build: ./ui
    container_name: sprintmont_fe
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_APP_ENV=production
    depends_on:
      - backend
    networks:
      - sprintmont_net

volumes:
  pg_data:
  redis_data:
  seaweed_data:

networks:
  sprintmont_net:
    driver: bridge